/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as PayTestRouteImport } from './routes/pay-test'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as RathYatraRouteImport } from './routes/rath-yatra'
import { Route as TravelersRouteImport } from './routes/travelers'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as ApiCreateOrderRouteImport } from './routes/api/create-order'
import { Route as ApiVerifyPaymentRouteImport } from './routes/api/verify-payment'
import { Route as ApiWalletPassRouteImport } from './routes/api/wallet-pass'
import { Route as DeskIndexRouteImport } from './routes/desk/index'
import { Route as DeskActionRouteImport } from './routes/desk/action'
import { Route as TripIdRouteImport } from './routes/trip.$id'
import { Route as VoucherCodeRouteImport } from './routes/voucher.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronFlagUnconfirmedRouteImport } from './routes/api/cron/flag-unconfirmed'
import { Route as ApiCronReconcileUnbookedRouteImport } from './routes/api/cron/reconcile-unbooked'
import { Route as ApiCronRefundRetryRouteImport } from './routes/api/cron/refund-retry'
import { Route as ApiInvoiceCodeRouteImport } from './routes/api/invoice.$code'
import { Route as ApiFunnelRouteImport } from './routes/api/funnel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTestRoute = PayTestRouteImport.update({
  id: '/pay-test',
  path: '/pay-test',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const RathYatraRoute = RathYatraRouteImport.update({
  id: '/rath-yatra',
  path: '/rath-yatra',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelersRoute = TravelersRouteImport.update({
  id: '/travelers',
  path: '/travelers',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateOrderRoute = ApiCreateOrderRouteImport.update({
  id: '/api/create-order',
  path: '/api/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPaymentRoute = ApiVerifyPaymentRouteImport.update({
  id: '/api/verify-payment',
  path: '/api/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletPassRoute = ApiWalletPassRouteImport.update({
  id: '/api/wallet-pass',
  path: '/api/wallet-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/desk/',
  path: '/desk/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskActionRoute = DeskActionRouteImport.update({
  id: '/desk/action',
  path: '/desk/action',
  getParentRoute: () => rootRouteImport,
} as any)
const TripIdRoute = TripIdRouteImport.update({
  id: '/trip/$id',
  path: '/trip/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VoucherCodeRoute = VoucherCodeRouteImport.update({
  id: '/voucher/$code',
  path: '/voucher/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronFlagUnconfirmedRoute = ApiCronFlagUnconfirmedRouteImport.update({
  id: '/api/cron/flag-unconfirmed',
  path: '/api/cron/flag-unconfirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronReconcileUnbookedRoute =
  ApiCronReconcileUnbookedRouteImport.update({
    id: '/api/cron/reconcile-unbooked',
    path: '/api/cron/reconcile-unbooked',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronRefundRetryRoute = ApiCronRefundRetryRouteImport.update({
  id: '/api/cron/refund-retry',
  path: '/api/cron/refund-retry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoiceCodeRoute = ApiInvoiceCodeRouteImport.update({
  id: '/api/invoice/$code',
  path: '/api/invoice/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFunnelRoute = ApiFunnelRouteImport.update({
  id: '/api/funnel',
  path: '/api/funnel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/pay-test': typeof PayTestRoute
  '/plan': typeof PlanRoute
  '/rath-yatra': typeof RathYatraRoute
  '/travelers': typeof TravelersRoute
  '/trips': typeof TripsRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/api/wallet-pass': typeof ApiWalletPassRoute
  '/desk/action': typeof DeskActionRoute
  '/trip/$id': typeof TripIdRoute
  '/voucher/$code': typeof VoucherCodeRoute
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/flag-unconfirmed': typeof ApiCronFlagUnconfirmedRoute
  '/api/cron/reconcile-unbooked': typeof ApiCronReconcileUnbookedRoute
  '/api/cron/refund-retry': typeof ApiCronRefundRetryRoute
  '/api/invoice/$code': typeof ApiInvoiceCodeRoute
  '/api/funnel': typeof ApiFunnelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/pay-test': typeof PayTestRoute
  '/plan': typeof PlanRoute
  '/rath-yatra': typeof RathYatraRoute
  '/travelers': typeof TravelersRoute
  '/trips': typeof TripsRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/api/wallet-pass': typeof ApiWalletPassRoute
  '/desk/action': typeof DeskActionRoute
  '/trip/$id': typeof TripIdRoute
  '/voucher/$code': typeof VoucherCodeRoute
  '/desk': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/flag-unconfirmed': typeof ApiCronFlagUnconfirmedRoute
  '/api/cron/reconcile-unbooked': typeof ApiCronReconcileUnbookedRoute
  '/api/cron/refund-retry': typeof ApiCronRefundRetryRoute
  '/api/invoice/$code': typeof ApiInvoiceCodeRoute
  '/api/funnel': typeof ApiFunnelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/pay-test': typeof PayTestRoute
  '/plan': typeof PlanRoute
  '/rath-yatra': typeof RathYatraRoute
  '/travelers': typeof TravelersRoute
  '/trips': typeof TripsRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/api/wallet-pass': typeof ApiWalletPassRoute
  '/desk/action': typeof DeskActionRoute
  '/trip/$id': typeof TripIdRoute
  '/voucher/$code': typeof VoucherCodeRoute
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/flag-unconfirmed': typeof ApiCronFlagUnconfirmedRoute
  '/api/cron/reconcile-unbooked': typeof ApiCronReconcileUnbookedRoute
  '/api/cron/refund-retry': typeof ApiCronRefundRetryRoute
  '/api/invoice/$code': typeof ApiInvoiceCodeRoute
  '/api/funnel': typeof ApiFunnelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/checkout'
    | '/login'
    | '/matches'
    | '/pay-test'
    | '/plan'
    | '/rath-yatra'
    | '/travelers'
    | '/trips'
    | '/api/create-order'
    | '/api/verify-payment'
    | '/api/wallet-pass'
    | '/desk/action'
    | '/trip/$id'
    | '/voucher/$code'
    | '/desk/'
    | '/api/auth/$'
    | '/api/cron/flag-unconfirmed'
    | '/api/cron/reconcile-unbooked'
    | '/api/cron/refund-retry'
    | '/api/invoice/$code'
    | '/api/funnel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/checkout'
    | '/login'
    | '/matches'
    | '/pay-test'
    | '/plan'
    | '/rath-yatra'
    | '/travelers'
    | '/trips'
    | '/api/create-order'
    | '/api/verify-payment'
    | '/api/wallet-pass'
    | '/desk/action'
    | '/trip/$id'
    | '/voucher/$code'
    | '/desk'
    | '/api/auth/$'
    | '/api/cron/flag-unconfirmed'
    | '/api/cron/reconcile-unbooked'
    | '/api/cron/refund-retry'
    | '/api/invoice/$code'
    | '/api/funnel'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/checkout'
    | '/login'
    | '/matches'
    | '/pay-test'
    | '/plan'
    | '/rath-yatra'
    | '/travelers'
    | '/trips'
    | '/api/create-order'
    | '/api/verify-payment'
    | '/api/wallet-pass'
    | '/desk/action'
    | '/trip/$id'
    | '/voucher/$code'
    | '/desk/'
    | '/api/auth/$'
    | '/api/cron/flag-unconfirmed'
    | '/api/cron/reconcile-unbooked'
    | '/api/cron/refund-retry'
    | '/api/invoice/$code'
    | '/api/funnel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  PayTestRoute: typeof PayTestRoute
  PlanRoute: typeof PlanRoute
  RathYatraRoute: typeof RathYatraRoute
  TravelersRoute: typeof TravelersRoute
  TripsRoute: typeof TripsRoute
  ApiCreateOrderRoute: typeof ApiCreateOrderRoute
  ApiVerifyPaymentRoute: typeof ApiVerifyPaymentRoute
  ApiWalletPassRoute: typeof ApiWalletPassRoute
  DeskActionRoute: typeof DeskActionRoute
  TripIdRoute: typeof TripIdRoute
  VoucherCodeRoute: typeof VoucherCodeRoute
  DeskIndexRoute: typeof DeskIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronFlagUnconfirmedRoute: typeof ApiCronFlagUnconfirmedRoute
  ApiCronReconcileUnbookedRoute: typeof ApiCronReconcileUnbookedRoute
  ApiCronRefundRetryRoute: typeof ApiCronRefundRetryRoute
  ApiInvoiceCodeRoute: typeof ApiInvoiceCodeRoute
  ApiFunnelRoute: typeof ApiFunnelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-test': {
      id: '/pay-test'
      path: '/pay-test'
      fullPath: '/pay-test'
      preLoaderRoute: typeof PayTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rath-yatra': {
      id: '/rath-yatra'
      path: '/rath-yatra'
      fullPath: '/rath-yatra'
      preLoaderRoute: typeof RathYatraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travelers': {
      id: '/travelers'
      path: '/travelers'
      fullPath: '/travelers'
      preLoaderRoute: typeof TravelersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-order': {
      id: '/api/create-order'
      path: '/api/create-order'
      fullPath: '/api/create-order'
      preLoaderRoute: typeof ApiCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-payment': {
      id: '/api/verify-payment'
      path: '/api/verify-payment'
      fullPath: '/api/verify-payment'
      preLoaderRoute: typeof ApiVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet-pass': {
      id: '/api/wallet-pass'
      path: '/api/wallet-pass'
      fullPath: '/api/wallet-pass'
      preLoaderRoute: typeof ApiWalletPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/desk'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/action': {
      id: '/desk/action'
      path: '/desk/action'
      fullPath: '/desk/action'
      preLoaderRoute: typeof DeskActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$id': {
      id: '/trip/$id'
      path: '/trip/$id'
      fullPath: '/trip/$id'
      preLoaderRoute: typeof TripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voucher/$code': {
      id: '/voucher/$code'
      path: '/voucher/$code'
      fullPath: '/voucher/$code'
      preLoaderRoute: typeof VoucherCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/flag-unconfirmed': {
      id: '/api/cron/flag-unconfirmed'
      path: '/api/cron/flag-unconfirmed'
      fullPath: '/api/cron/flag-unconfirmed'
      preLoaderRoute: typeof ApiCronFlagUnconfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reconcile-unbooked': {
      id: '/api/cron/reconcile-unbooked'
      path: '/api/cron/reconcile-unbooked'
      fullPath: '/api/cron/reconcile-unbooked'
      preLoaderRoute: typeof ApiCronReconcileUnbookedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/refund-retry': {
      id: '/api/cron/refund-retry'
      path: '/api/cron/refund-retry'
      fullPath: '/api/cron/refund-retry'
      preLoaderRoute: typeof ApiCronRefundRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoice/$code': {
      id: '/api/invoice/$code'
      path: '/api/invoice/$code'
      fullPath: '/api/invoice/$code'
      preLoaderRoute: typeof ApiInvoiceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/funnel': {
      id: '/api/funnel'
      path: '/api/funnel'
      fullPath: '/api/funnel'
      preLoaderRoute: typeof ApiFunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  PayTestRoute: PayTestRoute,
  PlanRoute: PlanRoute,
  RathYatraRoute: RathYatraRoute,
  TravelersRoute: TravelersRoute,
  TripsRoute: TripsRoute,
  ApiCreateOrderRoute: ApiCreateOrderRoute,
  ApiVerifyPaymentRoute: ApiVerifyPaymentRoute,
  ApiWalletPassRoute: ApiWalletPassRoute,
  DeskActionRoute: DeskActionRoute,
  TripIdRoute: TripIdRoute,
  VoucherCodeRoute: VoucherCodeRoute,
  DeskIndexRoute: DeskIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronFlagUnconfirmedRoute: ApiCronFlagUnconfirmedRoute,
  ApiCronReconcileUnbookedRoute: ApiCronReconcileUnbookedRoute,
  ApiCronRefundRetryRoute: ApiCronRefundRetryRoute,
  ApiInvoiceCodeRoute: ApiInvoiceCodeRoute,
  ApiFunnelRoute: ApiFunnelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
